### PR TITLE
Spike at timing out ssh.NewSession

### PR DESCRIPTION
**Pull request by msakrejda**
Obvious outstanding problem is that the timeout is hard-coded. Less
obvious outstanding problems probably abound.

Thoughts, @kr? We could pass an sshpool-specific config struct embedding `ssh.ClientConfig` to allow tweaking the timeout.

### CODE REVIEW

**Comment by kr** [comment]
I think the timeout value should go in Pool. Like this:

``` go
type Pool struct {
    // If nil, ssh.Dial is used.
    Dial func(net, addr string, config *ssh.ClientConfig) (*ssh.ClientConn, error)

    // Computes a key to distinguish ssh connections.
    // If nil, AddrUserKey is used.
    Key func(net, addr string, config *ssh.ClientConfig) string

    // Calls to Open that take longer than this to complete will
    // return an error. If 0, there is no timeout.
    Timeout time.Duration
}
```

For it to work as described in the code comment above,
we'd need to compute a deadline first thing, then use the
deadline in inner calls to Dial and NewSession.

For the implementation, I think the deadline version of
NewSession should be a separate function or method.
Open will be too confusing if it's inline.

Unit tests?

**Comment by kr** [comment]
Actually, don't know what I was thinking about that struct type.
It should be `done := make(chan bool)` and the closure should
set local variables `s` and `err` directly.

**Comment by msakrejda** [comment]
> For it to work as described in the code commend above, we'd need to compute a deadline first thing, then use the deadline in inner calls to Dial and NewSession.

So you're proposing to put a hard timeout on Open? I had a hunch that timing out NewSession more aggressively and re-trying on a new TCP connection may be worth doing, but on second thought, that's not really based on any evidence (except that non-dyno conns seem to be serviced quickly).

**Comment by msakrejda** [comment]
Also, should we / can we actually just use [TCPConn.SetDeadline](http://golang.org/pkg/net/#TCPConn.SetDeadline) here?

**Comment by kr** [comment]
> Also, should we / can we actually just use TCPConn.SetDeadline here?

Oh snap, we totally can!

We'll need to get ahold of the underlying net.TCPConn somehow.
The changes in https://github.com/kr/sshpool/tree/dial would be
one way to do that.

I'll go ahead and merge that branch. It'll break observatory builds
until we update for the new api.

To anyone else who's using this package: sorry if you are
inconvenienced by this!

**Comment by msakrejda** [comment]
> This might not matter after we use SetDeadline, but I think this function
> would be worth simplifying quite a bit:

Oh duh, of course.

**Comment by msakrejda** [comment]
Closing in favor of #2.

**Pull request closed without merging**
